### ISSUE TITLE
File naming problem

### ISSUE THREAD

**Issue by mrtamagotchi** [HektorW/vs-code-create-react-folder-component#10]
Hello!
First of all, thank you for a great plugin. I use it daily and it has really enhanced my workflow.

At the moment I'm experiencing a minor issue when it comes to the automatic file naming. When creating the component `Error404Page` the associated style-file gets the name (and pre-populated classname) `error404-page`. Maybe it's a good idea to split not only before capital letters but also before the first digit of a number?

This is really an edge case, and not sure it splitting it like this would mess up some other naming convention, but since you usually don't have numbers in component names I assume it's safe.

If this is interesting I could try to submit a PR.

Anyways, thanks and keep up the good work! 🥳

**Comment by HektorW** [comment]
Fixed in v2.0.1 🎉
